apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata: # kpt-merge: /pe0
  name: pe0
  annotations:
    internal.kpt.dev/upstream-identifier: 'cilium.io|CiliumBGPPeeringPolicy|default|pe0'
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/hostname: node1
  virtualRouters:
  # Peer with XR and advertise Pod CIDR
  - localASN: 65000
    exportPodCIDR: true
    mapSRv6VRFs: true
    neighbors:
    - peerAddress: "10.12.10.1/32"
      peerASN: 66000
